#Testing environment
version: "3.9"
services: 
  redis:
    image: bitnami/redis:latest
    hostname: redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks: 
      internal: 
        aliases:
          - redis
  postgres:
    image: postgres:13.4
    hostname: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks: 
      internal: 
        aliases:
          - postgres
    volumes: 
      - "${PWD}/initdb:/docker-entrypoint-initdb.d"
  node:
    build: .
    ports: 
      - "8080:80"
      - "2222:22"
      - "9229:9229"
    restart: unless-stopped
    environment: 
      - NODE_ENV=${NODE_ENV}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - EXPRESS_PORT=80
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - internal
networks: 
  internal: